@startuml
actor Usuario
Usuario -> MutantController: checkMutant(request): ResponseEntity
MutantController -> DnaRequest: getDna(): String[]
DnaRequest --> MutantController:
MutantController -> MutantService: analyzeDna(dna: String[]): boolean
MutantService -> MutantService: calculateHash(dna: String[]): String
MutantService -> DnaRepository: findByHash(hash: String): Optional<DnaRecord>
DnaRepository --> MutantService:
alt DnaRecord existe
MutantService -> DnaRecord: isMutant(): boolean
DnaRecord --> MutantService:
else DnaRecord no existe
MutantService -> MutantDetector: isMutant(dna: String[]): boolean
MutantDetector --> MutantService:
MutantService -> DnaRecord: create()
DnaRecord --> MutantService:
MutantService -> DnaRecord: setHash(hash: String)
DnaRecord --> MutantService:
MutantService -> DnaRecord: setMutant(isMutant: boolean)
DnaRecord --> MutantService:
MutantService -> DnaRepository: save(dnaRecord: DnaRecord):
DnaRepository --> MutantService:
end
MutantService --> MutantController: return isMutant: boolean
alt isMutant == true
MutantController -> ResponseEntity: ok().build(): ResponseEntity
ResponseEntity --> MutantController:
else
MutantController -> ResponseEntity: status(HttpStatus.FORBIDDEN).build(): ResponseEntity
ResponseEntity --> MutantController:
end
MutantController --> Usuario:

@enduml