@startuml
Actor Usuario
Usuario -> MutantController: getStats(): ResponseEntity<StatsResponse>
MutantController -> StatsService: getStats(): StatsResponse
StatsService -> DnaRecordRepository: countByIsMutantTrue(): long
DnaRecordRepository --> StatsService: mutantCount
StatsService -> DnaRecordRepository: countByIsMutantFalse(): long
DnaRecordRepository --> StatsService: humanCount
StatsService -> StatsService: calculateRatio(long mutantCount, long humanCount): double
StatsService -> StatsResponse: new StatsResponse(long mutantCount, long humanCount, double ratio): StatsResponse
StatsResponse --> StatsService: stastsResponse
StatsService --> MutantController: statsResponse
MutantController -> ResponseEntity: ok(statsResponse): ResponseEntity<StatsResponse>
ResponseEntity --> MutantController
MutantController --> Usuario: responseEntity
@enduml